// <auto-generated />
using LondonTubeNotifier.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LondonTubeNotifier.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250820152415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LondonTubeNotifier.Core.Domain.Entities.Line", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Id = "bakerloo",
                            Code = "BL",
                            Color = "#B36305",
                            Name = "Bakerloo"
                        },
                        new
                        {
                            Id = "central",
                            Code = "CL",
                            Color = "#E32017",
                            Name = "Central"
                        },
                        new
                        {
                            Id = "circle",
                            Code = "CC",
                            Color = "#FFD300",
                            Name = "Circle"
                        },
                        new
                        {
                            Id = "district",
                            Code = "DL",
                            Color = "#00782A",
                            Name = "District"
                        },
                        new
                        {
                            Id = "hammersmith-city",
                            Code = "HCL",
                            Color = "#F3A9BB",
                            Name = "Hammersmith & City"
                        },
                        new
                        {
                            Id = "jubilee",
                            Code = "JL",
                            Color = "#6A7278",
                            Name = "Jubilee"
                        },
                        new
                        {
                            Id = "metropolitan",
                            Code = "ML",
                            Color = "#9B0056",
                            Name = "Metropolitan"
                        },
                        new
                        {
                            Id = "northern",
                            Code = "NL",
                            Color = "#000000",
                            Name = "Northern"
                        },
                        new
                        {
                            Id = "piccadilly",
                            Code = "PL",
                            Color = "#0019A8",
                            Name = "Piccadilly"
                        },
                        new
                        {
                            Id = "victoria",
                            Code = "VL",
                            Color = "#0098D4",
                            Name = "Victoria"
                        },
                        new
                        {
                            Id = "waterloo-city",
                            Code = "WCL",
                            Color = "#95CDBA",
                            Name = "Waterloo & City"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
